cp lploc.js build/lploc.js
cp webcam.html build/webcam.html
cp exam.html build/exam.html
cp calibrate.html build
cp timer.js build
cp camvas.js build
cp login.css build
cp pico.js build
cp clarifications.js build
cp login.html build
cp video.html build
